name: birdbrain
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - notebook>5.2
  - ipywidgets
  - pandas
  - scipy
  - numba
  - scikit-image
  - vtk
  - tqdm
  - nipy
  - pip:
     - k3d
     - nibabel
     - birdbrain
     - unrar
     - patool
     - pyunpack
